# Generated by Django 5.2.7 on 2025-11-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_trader_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='Name',
            field=models.CharField(default='Distributor Baru'),
        ),
    ]
