# Generated by Django 5.2.7 on 2025-11-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_distributor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='Trader',
        ),
        migrations.AddField(
            model_name='factory',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.orderplatform'),
        ),
    ]
