# Generated by Django 5.2.7 on 2025-11-13 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_factory_trader_factory_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='Order',
        ),
        migrations.RenameField(
            model_name='costumer',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='Factory',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='Farmer',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='Production_Code',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='Process',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='Production_Code',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='Wrap',
        ),
        migrations.AddField(
            model_name='costumer',
            name='Lokasi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='QR_Code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='History', to='tracking.product')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderPlatform',
        ),
    ]
