# Generated by Django 5.2.7 on 2025-11-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_factory_order_remove_trader_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drying_Start', models.DateTimeField(blank=True, null=True)),
                ('Drying_End', models.DateTimeField(blank=True, null=True)),
                ('Pressing_Date', models.DateField(blank=True, null=True)),
                ('Packaging_Date', models.DateField(blank=True, null=True)),
                ('Packaging_Type', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProductFactory', to='tracking.product')),
            ],
        ),
    ]
