# Generated by Django 5.2.7 on 2025-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_productfactory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='Lokasi',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='Lokasi',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='factory',
            old_name='Factory_Name',
            new_name='FactoryName',
        ),
        migrations.RenameField(
            model_name='factory',
            old_name='Lokasi',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Kelompok_Tani',
            new_name='FarmerGroup',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Lokasi',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Nama',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Umur_Panen',
            new_name='HarvestAge',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Metode_Panen',
            new_name='HarvestMethod',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pemilik',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Kadar_Air',
            new_name='WaterContent',
        ),
        migrations.RenameField(
            model_name='productfactory',
            old_name='Drying_End',
            new_name='DryingEnd',
        ),
        migrations.RenameField(
            model_name='productfactory',
            old_name='Drying_Start',
            new_name='DryingStart',
        ),
        migrations.RenameField(
            model_name='productfactory',
            old_name='Packaging_Date',
            new_name='PackagingDate',
        ),
        migrations.RenameField(
            model_name='productfactory',
            old_name='Packaging_Type',
            new_name='PackagingType',
        ),
        migrations.RenameField(
            model_name='productfactory',
            old_name='Pressing_Date',
            new_name='PressingDate',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='Lokasi',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='Nama',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='productfactory',
            name='ProductionCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
