# Generated by Django 5.2.7 on 2025-11-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_rename_lokasi_costumer_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
    ]
