# Generated by Django 5.2.7 on 2025-11-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_rename_costumer_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='AsalDesa',
            field=models.CharField(choices=[('Laturake', 'Laturake'), ('Morekao', 'Morekao'), ('Ariate', 'Ariate'), ('Kawa', 'Kawa'), ('Alang Saude', 'Alang Saude'), ('Waisala', 'Waisala'), ('Kamal', 'Kamal'), ('Buria', 'Buria'), ('Lokki', 'Lokki'), ('Nagalema', 'Nagalema'), ('Tehoru', 'Tehoru'), ('Piru', 'Piru'), ('Taniwel', 'Taniwel'), ('Leimu', 'Leimu'), ('Lainnya', 'Lainnya')], default='Pilih Desa', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Location',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='Location',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='factory',
            name='Location',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Location',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='trader',
            name='Location',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
