# Generated by Django 5.2.7 on 2025-11-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_farmer_asaldesa_alter_customer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductFarmers',
            field=models.CharField(default='Tidak ada produk', max_length=100),
        ),
    ]
