# Generated by Django 5.2.7 on 2025-11-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_product_productfarmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Grade',
            field=models.CharField(blank=True, choices=[('basah', 'Basah'), ('kering', 'Kering'), ('campur', 'Campur'), ('abcd', 'ABCD atau AB'), ('bwp', 'BWP'), ('ss', 'SS'), ('whole', 'Whole'), ('broken', 'Broken'), ('tua', 'Tua'), ('muda', 'Muda'), ('lainnya', 'Lainnya')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductFarmers',
            field=models.CharField(choices=[('Pala Batok', 'Pala Batok'), ('Pala Bulat', 'Pala Bulat'), ('Pala Lonjong', 'Pala Lonjong'), ('Daging Pala', 'Daging Pala'), ('Fuli', 'Fuli'), ('Cengkeh', 'Cengkeh'), ('Kenari', 'Kenari'), ('Vanila', 'Vanila'), ('Kopi Tuni', 'Kopi Tuni'), ('Buah Pala Utuh', 'Buah Pala Utuh')], default='Tidak ada produk', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Varietas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
