# Generated by Django 5.2.7 on 2025-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_product_grade_alter_product_productfarmers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Grade',
            field=models.CharField(blank=True, choices=[('basah', 'Basah'), ('kering', 'Kering'), ('campur', 'Campur'), ('abcd', 'ABCD atau AB'), ('bwp', 'BWP'), ('ss', 'SS'), ('whole', 'Whole'), ('broken', 'Broken'), ('tua', 'Tua'), ('muda', 'Muda'), ('lainnya', 'Lainnya')], default='Kualitas', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Volume',
            field=models.FloatField(),
        ),
    ]
